# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-29 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fried',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid1', models.IntegerField(verbose_name='好友ID')),
                ('uid2', models.IntegerField(verbose_name='好友ID')),
            ],
        ),
        migrations.CreateModel(
            name='Swiped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='滑动人的ID')),
                ('sid', models.IntegerField(verbose_name='被滑动人的ID')),
                ('s_type', models.CharField(choices=[('like', '右滑：喜欢'), ('superlike', '上滑：超级喜欢'), ('dislike', '左滑：不喜欢')], max_length=10, verbose_name='滑动类型')),
                ('stime', models.DateTimeField(auto_now_add=True, verbose_name='滑动时间')),
            ],
        ),
    ]
