# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-29 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swiped',
            old_name='s_type',
            new_name='stype',
        ),
    ]
