# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-03 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0004_auto_20191129_1648'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='swiped',
            unique_together=set([('uid', 'sid')]),
        ),
    ]
